浏览器的JavaScript报告功能，可以及时收到错误通知。

## 错误处理

- try-catch语句

```javascript
try {
    // 可能会导致错误的代码
} catch (error) {
    // 错误发生时怎么处理
}
```
发生错误时，catch会接收到一个包含错误信息的对象，对象包含的实际信息会因为浏览器而有差异，但共同的是有一个保存着错误消息的message属性。

- finally子句：
- finally子句一经使用，其代码无论如何都会执行，甚至return语句，都不会阻止finally子句的执行。

```javascript
try {
    return 2;
} catch (error) {
    return 1;
} finally {
    return 0;
}
// 0
```


try...catch...中如果异步代码出错怎么办？  ？？？
- try-catch一般只能捕获同步任务中的错误，若是try中的同步任务出现了异步错误，catch是无法捕获到的，主要是因为，异步函数抛出异常后，宏任务已经进入了执行栈，不在try-catch的栈中，微任务只能用自带的错误捕获捕获
- 使用window.onerror这个全局错误捕获函数
- try-catch 中的异常只会抛出一层
- promise这种就用自己专属的错误处理
- 宏任务这种可以用onerror

全局错误的捕获
- window.onerror
    - 接收三个参数：错误消息，错误所在的URL和行号。


- 错误类型

|||
|:---:|:---:|
|Error|基类型|
|EvalError|eval函数发生异常时抛出|
|RangeError|数值超出相应范围时触发|
|ReferenceError|找不到对象的情况下会触发|
|SyntaxError|语法错误|
|TypeError|变量中保存着意外的类型或访问不存在的方法时|
|URIError|encodeURI或decodeURI，URI格式不正确|

- 抛出错误throw

用于随时抛出自定义错误，抛出错误时，必须给throw操作符指定一个值。

遇到throw操作符时，代码会立即停止执行。

使用某种内置错误类型，可以更真实的模拟浏览器错误。

利用原型链可以通过继承Error来创建自定义错误类型（组合继承）。p505

- 把错误记录到服务器

集中保存错误日志，以便查找重要错误的原因。